languageCode = "en"
languageName = "English"
weight = 1
title = "Romain Jouhameau"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "Blog"

[author]
name = "Romain Jouhameau"
headline = "Data Engineer"
# bio = "This blog serves as a platform for me to document my journey and share insights. It's a space for reflection, learning, and connecting with others who have similar interests."
image = "img/me.png"
links = [
  { github = "https://github.com/RomainEconomics" },
  { email = "mailto:jouhameau.romain@gmail.com" },
  { linkedin = "https://www.linkedin.com/in/jouhameau-romain-87064618b/" },
]
